version: "3.8"
services:
  ###########
  # FLIGHTS #
  ###########
  flights:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/am-flights-api
    hostname: flights-api
    container_name: flights-api
    ports:
      - 8081:8081
    env_file:
      - .env
    # resources
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 1

  #########
  # USERS #
  #########
  users:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/am-users-api
    hostname: users-api
    container_name: users-api
    ports:
      - 8083:8083
    env_file:
      - .env
    # resources
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 1

  ############
  # BOOKINGS #
  ############
  bookings:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/am-bookings-api
    hostname: bookings-api
    container_name: bookings-api
    ports:
      - 8082:8082
    env_file:
      - .env
    # resources
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 1

  ########
  # AUTH #
  ########
  auth:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/am-auth-api
    hostname: auth-api
    container_name: auth-api
    ports:
      - 8443:8443
    env_file:
      - .env
    # resources
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: 1
