version: "3.8"
services:
  flights:
    image: amattsonsm/flights-api
    hostname: flights-api
    container_name: flights-api
    ports:
      - 8081:8081
    env_file:
      - .env
  users:
    image: amattsonsm/users-api
    hostname: users-api
    container_name: users-api
    ports:
      - 8083:8083
    env_file:
      - .env
  bookings:
    image: amattsonsm/bookings-api
    hostname: bookings-api
    container_name: bookings-api
    ports:
      - 8082:8082
    env_file:
      - .env
  auth:
    image: amattsonsm/auth-api
    hostname: auth-api
    container_name: auth-api
    ports:
      - 8443:8443
    env_file:
      - .env
