version: "3.9"
x-aws-vpc: "${AWS_VPC_ID}"
x-aws-loadbalancer: "${AWS_ALB_ID}"
services:
  ###########
  # FLIGHTS #
  ###########
  flights:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-flights-api:latest"
    ports:
      - 8081:8081
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      resources:
        limits:
          cpus: "${ECS_CPU_LIMIT}"
          memory: "${ECS_MEM_LIMIT}"
        reservations:
          cpus: "${ECS_CPU_REQUEST}"
          memory: "${ECS_MEM_REQUEST}"

  #########
  # USERS #
  #########
  users:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-users-api:latest"
    ports:
      - 8083:8083
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      resources:
        limits:
          cpus: "${ECS_CPU_LIMIT}"
          memory: "${ECS_MEM_LIMIT}"
        reservations:
          cpus: "${ECS_CPU_REQUEST}"
          memory: "${ECS_MEM_REQUEST}"

  ############
  # BOOKINGS #
  ############
  bookings:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-bookings-api:latest"
    ports:
      - 8082:8082
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      resources:
        limits:
          cpus: "${ECS_CPU_LIMIT}"
          memory: "${ECS_MEM_LIMIT}"
        reservations:
          cpus: "${ECS_CPU_REQUEST}"
          memory: "${ECS_MEM_REQUEST}"

  ########
  # AUTH #
  ########
  auth:
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-auth-api:latest"
    ports:
      - 8443:8443
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      resources:
        limits:
          cpus: "${ECS_CPU_LIMIT}"
          memory: "${ECS_MEM_LIMIT}"
        reservations:
          cpus: "${ECS_CPU_REQUEST}"
          memory: "${ECS_MEM_REQUEST}"
