version: "3.9"
x-aws-vpc: "${AWS_VPC_ID}"
x-aws-loadbalancer: "${AWS_ALB_ID}"

networks:
  back_tier:
    external: true
    name: "${AWS_ECS_SG}"

services:
  ###########
  # FLIGHTS #
  ###########
  flights:
    x-aws-min_percent: 50
    x-aws-max_percent: 100
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-flights-api
    ports:
      - target: 8081
        x-aws-protocol: http
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: $ECS_REPLICAS
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"

  #########
  # USERS #
  #########
  users:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-users-api
    ports:
      - target: 8083
        x-aws-protocol: http
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: $ECS_REPLICAS
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"

  ############
  # BOOKINGS #
  ############
  bookings:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-bookings-api
    ports:
      - target: 8082
        x-aws-protocol: http
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: ${ECS_REPLICAS}
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"

  ########
  # AUTH #
  ########
  auth:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-auth-api
    ports:
      - target: 8443
        x-aws-protocol: http
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: $ECS_REPLICAS
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"

# Cloudformation Override
x-aws-cloudformation:
  Resources:

    # Services use Private Subnets
    FlightsService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}
    UsersService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}
    BookingsService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}
    AuthService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}

    # Target Groups use adapted healthcheck paths
    Flights8081TargetGroup:
      Properties:
        HealthCheckPath: /api/v1/flights/ready
    Bookings8082TargetGroup:
      Properties:
        HealthCheckPath: /api/v1/bookings/ready
    Users8083TargetGroup:
      Properties:
        HealthCheckPath: /api/v1/users/ready
    Auth8443TargetGroup:
      Properties:
        HealthCheckPath: /api/v1/login/ready
