version: "3.9"
x-aws-vpc: "${AWS_VPC_ID}"

networks:
  back_tier:
    external: true
    name: "${AWS_ECS_SG}"

services:
  ###########
  # FLIGHTS #
  ###########
  flights:
    x-aws-min_percent: 50
    x-aws-max_percent: 100
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-flights-api
    ports:
      - 8081:8081
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: $ECS_REPLICAS
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"

  #########
  # USERS #
  #########
  users:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-users-api
    ports:
      - 8083:8083
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: $ECS_REPLICAS
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"

  ############
  # BOOKINGS #
  ############
  bookings:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-bookings-api
    ports:
      - 8082:8082
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: ${ECS_REPLICAS}
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"

  ########
  # AUTH #
  ########
  auth:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-auth-api
    ports:
      - 8443:8443
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: $ECS_REPLICAS
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"

# Subnet Override
x-aws-cloudformation:
  Resources:
    flights:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}
    users:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}
    bookings:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}
    auth:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}
    LoadBalancer:
      Properties:
        Subnets:
          - ${PUBLIC_SUBNET_1}
          - ${PUBLIC_SUBNET_2}
