version: "3.9"
x-aws-vpc: "${AWS_VPC_ID}"
x-aws-loadbalancer: "${AWS_ALB_ID}"

networks:
  back_tier:
    external: true
    name: "${AWS_ECS_SG}"

services:
  ###########
  # FLIGHTS #
  ###########
  flights:
    x-aws-min_percent: 50
    x-aws-max_percent: 100
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-flights-api
    ports:
      - target: 8081
        x-aws-protocol: http
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: $ECS_REPLICAS
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"


  #########
  # USERS #
  #########
  users:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-users-api
    ports:
      - target: 8083
        x-aws-protocol: http
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: $ECS_REPLICAS
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"


  ############
  # BOOKINGS #
  ############
  bookings:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-bookings-api
    ports:
      - target: 8082
        x-aws-protocol: http
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: ${ECS_REPLICAS}
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"


  ########
  # AUTH #
  ########
  auth:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_ID}.amazonaws.com/am-auth-api
    ports:
      - target: 8443
        x-aws-protocol: http
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_CONNECTION_POOL_MIN=${DB_POOL_MIN}
      - DB_CONNECTION_POOL_MAX=${DB_POOL_MAX}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
    deploy:
      replicas: $ECS_REPLICAS
      resources:
        limits:
          cpus: "$ECS_CPU_LIMIT"
          memory: "$ECS_MEM_LIMIT"
        reservations:
          cpus: "$ECS_CPU_REQUEST"
          memory: "$ECS_MEM_REQUEST"



# Cloudformation Override
x-aws-cloudformation:
  Resources:

    # Services should use Private Subnets
    FlightsService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}
    UsersService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}
    BookingsService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}
    AuthService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${PRIVATE_SUBNET_1}
              - ${PRIVATE_SUBNET_2}


    # Target Groups should use adapted healthcheck paths
    Flights8081TargetGroup:
      Properties:
        HealthCheckPath: /api/v1/flights/ready
    Bookings8082TargetGroup:
      Properties:
        HealthCheckPath: /api/v1/bookings/ready
    Users8083TargetGroup:
      Properties:
        HealthCheckPath: /api/v1/users/ready
    Auth8443TargetGroup:
      Properties:
        HealthCheckPath: /api/v1/login/ready


    # Custom Listener for HTTP on port 80
    UtopiaListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - Type: forward
            ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: Auth8443TargetGroup
        Port: 80
        Protocol: HTTP
        LoadBalancerArn: ${AWS_ALB_ID}


    # Listeners need custom rules for paths
    Flights8081ListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      DependsOn:
        - UtopiaListener
        - Flights8081TargetGroup
      Properties:
        Actions:
          - Type: forward
            TargetGroupArn:
              Ref: Flights8081TargetGroup
        Conditions:
          - Field: path-pattern
            PathPatternConfig:
              Values:
                - "/api/v1/flights"
                - "/api/v1/flights/*"
                - "/api/v1/airports"
                - "/api/v1/airports/*"
        ListenerArn:
          Ref: UtopiaListener
        Priority: 9
    Bookings8082ListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      DependsOn:
        - UtopiaListener
        - Bookings8082TargetGroup
      Properties:
        Actions:
          - Type: forward
            TargetGroupArn:
              Ref: Bookings8082TargetGroup
        Conditions:
          - Field: path-pattern
            PathPatternConfig:
              Values:
                - "/api/v1/bookings"
                - "/api/v1/bookings/*"
                - "/api/v1/payments"
                - "/api/v1/payments/*"
                - "/api/v1/passengers"
                - "/api/v1/passengers/*"
        ListenerArn:
          Ref: UtopiaListener
        Priority: 8
    Users8083ListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      DependsOn:
        - UtopiaListener
        - Users8083TargetGroup
      Properties:
        Actions:
          - Type: forward
            TargetGroupArn:
              Ref: Users8083TargetGroup
        Conditions:
          - Field: path-pattern
            PathPatternConfig:
              Values:
                - "/api/v1/users"
                - "/api/v1/users/*"
                - "/api/v1/roles"
                - "/api/v1/roles/*"
        ListenerArn:
          Ref: UtopiaListener
        Priority: 7
    Auth8443ListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      DependsOn:
        - UtopiaListener
        - Auth8443TargetGroup
      Properties:
        Actions:
          - Type: forward
            TargetGroupArn:
              Ref: Auth8443TargetGroup
        Conditions:
          - Field: path-pattern
            PathPatternConfig:
              Values:
                - "/api/v1/login/ready"
                - "/login"
        ListenerArn:
          Ref: UtopiaListener
        Priority: 6
