version: "3.8"
x-aws-vpc: "${AWS_VPC_ID}"
x-aws-loadbalancer: "${AWS_ALB_ID}"
services:
  ###########
  # FLIGHTS #
  ###########
  flights:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/am-flights-api
    ports:
      - 8081:8081
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306


  #########
  # USERS #
  #########
  users:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/am-users-api
    ports:
      - 8083:8083
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306

  ############
  # BOOKINGS #
  ############
  bookings:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/am-bookings-api
    ports:
      - 8082:8082
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306

  ########
  # AUTH #
  ########
  auth:
    image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/am-auth-api
    ports:
      - 8443:8443
    environment:
      - DB_USERNAME=${AWS_RDS_USERNAME}
      - DB_PASSWORD=${AWS_RDS_PASSWORD}
      - DB_ADDRESS=${AWS_RDS_ENDPOINT}
      - DB_NAME=utopia
      - DB_TYPE=mysql
      - DB_PORT=3306
