pipeline {
    agent {label 'aws-ready'}
    environment {
        AWS_RDS_USERNAME = credentials('AM_DB_USERNAME')
        AWS_RDS_PASSWORD = credentials('AM_DB_PASSWORD')
    }
    stages {
        stage('Load Environment') {
            steps {
                echo 'Loading Environment'
                script {
                    def outputs = readProperties file: '/var/lib/jenkins-worker-node/AM-resources/env.tf'
                    env.AWS_VPC_ID = outputs.AWS_VPC_ID
                    env.AWS_RDS_ENDPOINT = outputs.AWS_RDS_ENDPOINT
                    env.AWS_ALB_ID = outputs.AWS_ALB_ID
                }
                sh 'echo Environment loaded: VPC = ${AWS_VPC_ID} ----- RDS = ${AWS_RDS_ENDPOINT}'
            }
        }
        stage('Push ECS') {
            steps {
                echo 'Configuring ECS'
                dir("ecs") {
                    sh 'docker context use am_aws_ecs'
                    sh 'docker compose up --no-color'
                }
            }
        }
    }
}
