
- name: check if EKS is up
  shell: eksctl get cluster --region {{eks_aws_region}} --verbose 0
  register: eks_check_cluster

- name: create EKS cluster
  community.aws.aws_eks_cluster:
    name: {{eks_clustername}}
    version: {{eks_clusterversion}}
    role_arn: {{tf_eks_iam_role_arn}}
    subnets:
      - {{tf_subnet_public_1}}
      - {{tf_subnet_public_2}}
    security_groups:
      - {{tf_eks_security_group}}
  when: '"{{eks_clustername}}" not in eks_check_cluster.stdout'

