apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth-deploy
  labels:
    app: api-auth-app
spec:
  selector:
    matchLabels:
      app: api-auth-app
  replicas: 1
  template:
    metadata:
      labels:
        app: api-auth-app
    spec:
      containers:
        - name: api-auth-app
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION_ID.amazonaws.com/am-auth-api:$AUTH_API_LATEST
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "900m"
              memory: "1024Mi"
            requests:
              cpu: "350m"
              memory: "512Mi"
          ports:
            - containerPort: 8443
          env:
            - name: DB_ADDRESS
              valueFrom:
                secretKeyRef:
                  key: DB_ADDRESS
                  name: utopia-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: DB_NAME
                  name: utopia-secret
            - name: DB_TYPE
              valueFrom:
                secretKeyRef:
                  key: DB_TYPE
                  name: utopia-secret
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: DB_PORT
                  name: utopia-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: utopia-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: utopia-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-auth-service
  labels:
    app: api-auth-app
spec:
  ports:
    - protocol: TCP
      port: 8443
      name: http
  selector:
    app: api-auth-app
