apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-flights-deploy
  labels:
    app: api-flights-app
spec:
  selector:
    matchLabels:
      app: api-flights-app
  replicas: 1
  template:
    metadata:
      labels:
        app: api-flights-app
    spec:
      containers:
        - name: api-flights-app
          image: amattsonsm/flights-api:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL_SPRING
              valueFrom:
                secretKeyRef:
                  key: DB_URL_SPRING
                  name: utopia-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: utopia-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: utopia-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-flights-service
  labels:
    app: api-flights-app
spec:
  ports:
    - protocol: TCP
      port: 8081
      name: http
  selector:
    app: api-flights-app
