apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress-http
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/airports
            pathType: Prefix
            backend:
              service:
                name: api-flights-service
                port:
                  number: 8081
          - path: /api/v1/routes
            pathType: Prefix
            backend:
              service:
                name: api-flights-service
                port:
                  number: 8081
          - path: /api/v1/airplanes
            pathType: Prefix
            backend:
              service:
                name: api-flights-service
                port:
                  number: 8081
          - path: /api/v1/airplaneTypes
            pathType: Prefix
            backend:
              service:
                name: api-flights-service
                port:
                  number: 8081
          - path: /api/v1/flights
            pathType: Prefix
            backend:
              service:
                name: api-flights-service
                port:
                  number: 8081
          ########################
          # BOOKINGS API SERVICE #
          ########################
          - path: /api/v1/bookings
            pathType: Prefix
            backend:
              service:
                name: api-bookings-service
                port:
                  number: 8082
          - path: /api/v1/passengers
            pathType: Prefix
            backend:
              service:
                name: api-bookings-service
                port:
                  number: 8082
          - path: /api/v1/payments
            pathType: Prefix
            backend:
              service:
                name: api-bookings-service
                port:
                  number: 8082
