apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-users-deploy
  labels:
    app: api-users-app
spec:
  selector:
    matchLabels:
      app: api-users-app
  replicas: 1
  template:
    metadata:
      labels:
        app: api-users-app
    spec:
      containers:
        - name: api-users-app
          image: 026390315914.dkr.ecr.us-west-2.amazonaws.com/am-users-api:$USERS_API_LATEST
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "900m"
              memory: "1024Mi"
            requests:
              cpu: "350m"
              memory: "512Mi"
          ports:
            - containerPort: 8083
          env:
            - name: DB_ADDRESS
              valueFrom:
                secretKeyRef:
                  key: DB_ADDRESS
                  name: utopia-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: DB_NAME
                  name: utopia-secret
            - name: DB_TYPE
              valueFrom:
                secretKeyRef:
                  key: DB_TYPE
                  name: utopia-secret
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: DB_PORT
                  name: utopia-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: utopia-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: utopia-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-users-service
  labels:
    app: api-users-app
spec:
  ports:
    - protocol: TCP
      port: 8083
      name: http
  selector:
    app: api-users-app
