pipeline {
    agent {
        node {
            label 'aws-ready'
            customWorkspace "${AM_DEVOPS_DIRECTORY}"
        }
    }

    environment {

        // AWS references
        AWS_SECRET_ID             = 'dev/AM/utopia-secrets'
        AWS_PROFILE               = "${AWS_PROFILE_NAME}"
        AWS_ACCESS_KEY            = credentials('AM_AWS_ACCESS')
        AWS_SECRET_KEY            = credentials('AM_AWS_SECRET')

        // Ansible AWS Info
        ANSIBLE_AWS_REGION_ID             = ${AWS_REGION_ID}
        ANSIBLE_AWS_ACCOUNT_ID            = ${AWS_ACCOUNT_ID}
        ANSIBLE_AWS_HOSTED_ZONE_ID        = ${AWS_HOSTED_ZONE_ID}
        ANSIBLE_AWS_SECRET_ID             = #{AWS_SECRET_ID}

        // Ansible API Info
        ANSIBLE_DB_POOL_MIN               = 2
        ANSIBLE_DB_POOL_MAX               = 4

        // Ansible EKS specific
        // for t2.medium: 1930m cpu, 3332Mi, 4 pods max
        ANSIBLE_EKS_CONTAINER_CPU_LIMIT   = "450m"
        ANSIBLE_EKS_CONTAINER_CPU_REQUEST = "250m"
        ANSIBLE_EKS_CONTAINER_MEM_LIMIT   = "800Mi"
        ANSIBLE_EKS_CONTAINER_MEM_REQUEST = "400Mi"
        ANSIBLE_EKS_REPLICA_COUNT         = 2

        // Ansible Tower Config
        TOWER_ENDPOINT          = "https://am-ansible.hitwc.link"
        TOWER_JOBNUM            = "11"
        TOWER_WEBHOOK           = "${ANSIBLE_ENDPOINT}/api/v2/job_templates/${ANSIBLE_JOBNUM}/launch/"
    }

    stages {
        stage('Load Environment') {
            steps {
                sh 'aws configure set region ${AWS_REGION_ID} --profile ${AWS_PROFILE_NAME}'
                script {
                    secret = sh(returnStdout: true, script: 'aws secretsmanager get-secret-value --secret-id ${AWS_SECRET_ID} | jq -Mr \'.SecretString\'').trim()
                    def jsonObj = readJSON text: secret
                    env.AWS_RDS_USERNAME    = jsonObj.DB_USERNAME
                    env.AWS_RDS_PASSWORD    = jsonObj.DB_PASSWORD
                    env.AWS_RDS_ENDPOINT    = jsonObj.AWS_RDS_ENDPOINT
                    env.ANSIBLE_AUTH        = jsonObj.ANSIBLE_TOKEN
                    env.ANSIBLE_EKS_RECORD_NAME = sh(returnStdout: true, script: "cd ${AM_DEVOPS_DIRECTORY}/terraform; terraform output | grep EKS_RECORD | sed 's/.*= //; s/\"//g'")
                }
            }
        }

        stage('Load Images') {
            steps {
                echo "Loading latest image hashes"
                dir("${AM_RESOURCES_DIRECTORY}") {
                    script {
                        env.USERS_API_LATEST = sh(script:'jq -Mr \'.users\' images-${AWS_REGION_ID}.json', returnStdout: true)
                        env.BOOKINGS_API_LATEST = sh(script:'jq -Mr \'.bookings\' images-${AWS_REGION_ID}.json', returnStdout: true)
                        env.FLIGHTS_API_LATEST = sh(script:'jq -Mr \'.flights\' images-${AWS_REGION_ID}.json', returnStdout: true)
                        env.AUTH_API_LATEST = sh(script:'jq -Mr \'.auth\' images-${AWS_REGION_ID}.json', returnStdout: true)
                    }
                }
            }
        }

        stage('Push EKS') {
            steps {
                echo 'Running Kubernetes Initialization'
                dir("${AM_DEVOPS_DIRECTORY}/ansible") {
                    echo "Getting required Environment Variables as YAML"
                    sh "env | grep 'ANSIBLE_' | sed -r 's/[ANSIBLE_]+//g' | sed -r 's/[=]+/: /g' > tmp_env.yaml"

                    echo "Converting YAML to JSON"
                    sh "python -c 'import json, yaml, sys; print(json.dumps(yaml.safe_load(sys.stdin)))' < tmp_env.yaml > tmp_env.json"

                    echo "Formatting for Ansible (extra_vars: )"
                    sh "jq -n -M --argjson insert \"\$(<tmp_env.json)\" '{extra_vars: \$insert}' > tmp_env_done.json"

                    echo "Posting to Ansible Tower"
                    sh "curl -X POST -k ${TOWER_WEBHOOK} -H \"Content-Type: application/json\" -H \"Authorization: Bearer ${ANSIBLE_AUTH}\" -d \"@tmp_env_done.json\""
                }
            }
        }

        stage('Cleanup') {
            steps {
                echo 'Cleaning temp files'
                dir("${AM_DEVOPS_DIRECTORY}/ansible") {
                    sh 'rm tmp_env*'
                }
            }
        }

        // end stages
    }
}
