---
- name: Create EC2 resources
  hosts: localhost

  vars:
    aws_region: us-west-1
    vpc_cidr: 10.0.0.0/16
    vpc_subnet_public_1_cidr: 10.0.0.0/20
    ec2_ami_image: ami-054965c6cd7c6e462
    ec2_ssh_keyname: bastion_key_cf

  tasks:
    - name: Create a VPC
      ec2_vpc_net:
        name: AM-ansible-VPC
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ aws_region }}"
        tenancy: default
      register: AM_ansible_VPC

    - name: Create IGW
      ec2_vpc_igw:
        vpc_id: "{{ AM_ansible_VPC.vpc.id }}"
        region: "{{ aws_region }}"
        state: present
      register: AM_ansible_IGW

    - name: Create a Public Subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ AM_ansible_VPC.vpc.id }}"
        cidr: "{{ vpc_subnet_public_1_cidr }}"
        region: "{{ aws_region }}"
      register: AM_ansible_subnet_public_1

    - name: Create Public Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ AM_ansible_VPC.vpc.id }}"
        region: "{{ aws_region }}"
        subnets:
          - "{{ AM_ansible_subnet_public_1.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ AM_ansible_IGW.gateway.id }}"

    - name: Create Security Group
      ec2_group:
        name: AM-ansible-SG
        description: Ansible Security Group for EC2 access
        vpc_id: "{{ AM_ansible_VPC.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow all SSH

    - name: Create a RHEL8 EC2 instance
      ec2:
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ AM_ansible_subnet_public_1.subnet.id }}"
        group: AM-ansible-SG
        count: 1
        instance_type: t2.micro
        wait: yes
        assign_public_ip: yes
        key_name: "{{ ec2_ssh_keyname }}"
        image: "{{ ec2_ami_image }}"
      register: AM_ansible_ec2_instance

    - name: Show Instance details - debug
      debug:
        msg: "Access at: {{ AM_ansible_ec2_instance.instances[0].public_ip }}"
