---

###############################################
#    EKS Destroy Module                       #
###############################################
#
# Required Variables (passed as extra_vars to Ansible Tower):
#
#    - AWS_REGION_ID
#
###############################################
#    EKS Destroy Module                       #
###############################################

- name: Destroy EKS created resources
  hosts: localhost
  connection: local
  vars:
    eks_location: "../kubernetes"
    eks_ingress_namespace: nginx-ingress
    eks_api_namespace: apis-ns
  tasks:

    #########################
    # Secrets and Variables #
    #########################
    - name: Get Utopia Secrets
      debug:
        msg: "{{ lookup('aws_secret', 'dev/AM/utopia-secrets') }}"
      register: utopia_secret

    ##################
    # Access Cluster #
    ##################
    - name: Access Cluster
      shell: |
        aws eks --region {{AWS_REGION_ID}} update-kubeconfig --name {{utopia_secret.msg.AWS_EKS_CLUSTER_NAME}}

    #####################
    # Destroy Resources #
    #####################
    - name: Destroy LoadBalancer Service
      k8s:
        state: absent
        namespace: "{{eks_ingress_namespace}}"
        api_version: v1
        kind: Service
        name: nginx-ingress

    - name: Destroy Utopia Secret
      k8s:
        state: absent
        namespace: "{{eks_api_namespace}}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: utopia-secret

    - name: Destroy APIs
      k8s:
        state: absent
        namespace: "{{eks_api_namespace}}"
        definition:
          label_selector:
            group: utopia
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            group: utopia
