- name: Setup EKS
  hosts: localhost
  gather_facts: no

  vars:
    ansible_user: ec2-user

  tasks:
    # Must be Ansible 2.8 or greater
    - name: Confirm Ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    # Import static
    - name: import static var data
      include_vars:
        dir: vars/static/eks
        ignore_unknown_extensions: True
        extensions:
          - yaml

    # Import dynamic
    - name: import dynamic var data
      include_vars:
        dir: vars/dynamic/eks
        ignore_unknown_extensions: True
        extensions:
          - yaml

    # Run EKS tasks
    - name: Set up EKS and any additional infrastructure
      include_tasks: "{{ item }}"
      loop:
        - ./tasks/eks-cluster-create.yaml
