---

###############################################
#    EKS Destroy Module                       #
###############################################
#
# Required Variables (passed as extra_vars to Ansible Tower):
#
#    - AWS_REGION_ID
#
###############################################
#    EKS Destroy Module                       #
###############################################

- name: Destroy EKS created resources
  hosts: localhost
  connection: local
  vars:
    eks_location: "../kubernetes"
    eks_ingress_namespace: nginx-ingress
    eks_api_namespace: apis-ns
  tasks:

    #########################
    # Secrets and Variables #
    #########################
    - name: Get Utopia Secrets
      debug:
        msg: "{{ lookup('aws_secret', '{{DEPLOY_MODE}}/AM/utopia-secrets') }}"
      register: utopia_secret

    ##################
    # Access Cluster #
    ##################
    - name: Access Cluster
      shell: |
        aws eks --region {{AWS_REGION_ID}} update-kubeconfig --name {{utopia_secret.msg.AWS_EKS_CLUSTER_NAME}}

    #####################
    # Destroy Resources #
    #####################
    - name: Destroy API Resources
      shell: |
        kubectl delete all -n {{eks_api_namespace}} -l group=utopia

    - name: Destroy Utopia Secret
      k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: utopia-secret
        namespace: "{{eks_api_namespace}}"

    - name: Destroy Ingress Resources
      shell: |
        kubectl delete -f . -n {{eks_ingress_namespace}}
      args:
        chdir: "{{ eks_location }}/nginx-ingress-config"
