---
- name: Test pushing variables
  hosts: localhost
  connection: local
  vars:
    testvar: thing
  tasks:
    - name: Load Variables
      debug:
        msg: "Variable is {{ testvar }}"

    - name: Other Variable
      debug:
        msg: "Passed variable is {{ SECRET_ID }}"

    - name: Get Secret
      debug:
        msg: "{{ lookup('aws_secret', 'dev/AM/utopia-secrets') }}"
      register: stored_secret

    - name: Use Secret
      debug:
        msg: "{{ stored_secret.msg.AWS_EKS_CLUSTER_NAME }}"

    - name: Show environment
      shell: |
        ls -la ../kubernetes
        pwd
        env
      register: envout

    - name: List results
      debug: var=envout.stdout

