---
- name: Stop Utopia Instances
  hosts: localhost
  connection: local
  vars_files:
    - ./ansible_varfile.yaml
  tasks:
    - name: Stop Instances
      ec2:
        instance_tags:
          Name: "{{EC2_INSTANCE_NAME}}"
        state: terminated
        region: "{{EC2_REGION_ID}}"


# ANSIBLE_NOCOLOR=True ansible-playbook start-apis.yaml --connection=local -e "ansible_python_interpreter=/usr/bin/python3" --tags=ec2-create
# ANSIBLE_NOCOLOR=True ansible-playbook stop-apis.yaml --connection=local -e "ansible_python_interpreter=/usr/bin/python3"
